import Image from "next/image";
import Link from "next/link";
import { RiRadioButtonFill } from "react-icons/ri";
import { useRouter } from "next/router";
import { projectData } from "../../../projectsData";
import Head from "next/head";
import { useEffect, useState } from "react";

const Index = () => {
  const [data, setData] = useState(projectData);
  const router = useRouter();
  const { id } = router.query;
  let isMatch = data.find((item) => {
    if (id == item.id) {
      return item;
    }
  });

  return (
    <div className="w-full">
      <Head>
        <title>Sean | Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" h-[40vh] lg:h-[50vh] relative">
        <div className="absolute top-0 left-0 w-full h-[40vh] lg:h-[50vh] bg-black/80 z-10"></div>
        <Image
          alt="#"
          src={isMatch?.img}
          className="absolute z-1"
          layout="fill"
          objectFit="cover"
        />
        <div className="absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] text-white z-20 px-7">
          <h2 className="py-2 capitalize">{isMatch?.name}</h2>
          <h3 className="capitalize">{isMatch?.overviewTech}</h3>
        </div>
      </div>

      <div className="max-w-[1240px] mx-auto p-2 grid md:grid-cols-5 gap-8 pt-8 px-7">
        <div className="col-span-4">
          <p className="capitalize text-[#5651e5]">project</p>
          <h2 className="capitalize">overview</h2>
          <p className="capitalize my-3">{isMatch?.projectInfo}</p>

          <Link href={isMatch.demo} target="_blank">
            <button className="px-8 py-2 mr-8 capitalize">demo</button>
          </Link>
          <Link href={isMatch.code} target="_blank">
            <button className="px-8 py-2 capitalize">code</button>
          </Link>
        </div>
        <div className="col-span-4 md:col-span-1 shadow-lg shadow-gray-400 p-4 rounded-xl">
          <div className="p-2">
            <p className="text-center capitalize font-semibold pb-2">
              technologies
            </p>
            <div className="grid grid-cols-3 md:grid-cols-1">
              {isMatch?.technologies.map((item) => (
                <p
                  className="text-gray-600 py-2 flex items-center capitalize"
                  key={item}
                >
                  <RiRadioButtonFill className="pr-1" />
                  {item}
                </p>
              ))}
            </div>
          </div>
        </div>
        <Link href={"/#projects"}>
          <p className="underline cursor-pointer capitalize">back</p>
        </Link>
      </div>
    </div>
  );
};

export default Index;
